### ISSUE TITLE
Ionization cross-section calculation

### ISSUE THREAD

**Issue by atpchris** [flexible-atomic-code/fac#723]
Hi,
I am working on the electron-impact ionization cross-section calculations using BED, DW, and CB methods. At near-threshold energies, noticeable deviations are observed due to obvious reasons. However, at high electron energies (100 times the threshold), significant discrepancies persist between the methods. Could you please suggest potential reasons for these differences at higher electron energies? Additionally, what steps could be taken to improve convergence between these approaches at high electron energies?
Thank you

**Comment by mfgu** [comment]
these methods don't necessarily converge at high energies. CB is based on fitting formula from Zhang&Sampson, PRA 42, 5378. they should be close to DW at high energies, but numerical differences can persist. BED is a somewhat empirical theory, the way it goes over to the Bethe approximation is different from DW. also the partial wave convergence can become a problem at very high energies with DW, in which case, the PWB mode should be used. DWB and PWB really should be combined such that DWB goes over to PWB at high energies. this is not implemented because DWB is too slow to begin with, and not frequently used.
